/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.114.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arvancloud

import (
	"encoding/json"
	"time"
)

// checks if the LoadBalancerUpdatePoolsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoadBalancerUpdatePoolsInner{}

// LoadBalancerUpdatePoolsInner struct for LoadBalancerUpdatePoolsInner
type LoadBalancerUpdatePoolsInner struct {
	Origins []LoadBalancerOriginStore `json:"origins,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Status *bool `json:"status,omitempty"`
	// Zero means the default pool
	Priority *int32 `json:"priority,omitempty"`
	Method *string `json:"method,omitempty"`
	Keepalive *string `json:"keepalive,omitempty"`
	// Try another server when the first one failed if on
	NextUpstreamTcp *string `json:"next_upstream_tcp,omitempty"`
	NextUpstreamTcpCodes *NextUpstreamTcpCodes `json:"next_upstream_tcp_codes,omitempty"`
	Regions []string `json:"regions,omitempty"`
	MonitoringStatus NullableMonitoringStatus `json:"monitoring_status,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewLoadBalancerUpdatePoolsInner instantiates a new LoadBalancerUpdatePoolsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoadBalancerUpdatePoolsInner() *LoadBalancerUpdatePoolsInner {
	this := LoadBalancerUpdatePoolsInner{}
	var keepalive string = "off"
	this.Keepalive = &keepalive
	var nextUpstreamTcp string = "off"
	this.NextUpstreamTcp = &nextUpstreamTcp
	return &this
}

// NewLoadBalancerUpdatePoolsInnerWithDefaults instantiates a new LoadBalancerUpdatePoolsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoadBalancerUpdatePoolsInnerWithDefaults() *LoadBalancerUpdatePoolsInner {
	this := LoadBalancerUpdatePoolsInner{}
	var keepalive string = "off"
	this.Keepalive = &keepalive
	var nextUpstreamTcp string = "off"
	this.NextUpstreamTcp = &nextUpstreamTcp
	return &this
}

// GetOrigins returns the Origins field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetOrigins() []LoadBalancerOriginStore {
	if o == nil || IsNil(o.Origins) {
		var ret []LoadBalancerOriginStore
		return ret
	}
	return o.Origins
}

// GetOriginsOk returns a tuple with the Origins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetOriginsOk() ([]LoadBalancerOriginStore, bool) {
	if o == nil || IsNil(o.Origins) {
		return nil, false
	}
	return o.Origins, true
}

// HasOrigins returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasOrigins() bool {
	if o != nil && !IsNil(o.Origins) {
		return true
	}

	return false
}

// SetOrigins gets a reference to the given []LoadBalancerOriginStore and assigns it to the Origins field.
func (o *LoadBalancerUpdatePoolsInner) SetOrigins(v []LoadBalancerOriginStore) {
	o.Origins = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LoadBalancerUpdatePoolsInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LoadBalancerUpdatePoolsInner) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *LoadBalancerUpdatePoolsInner) SetDescription(v string) {
	o.Description = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *LoadBalancerUpdatePoolsInner) SetStatus(v bool) {
	o.Status = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *LoadBalancerUpdatePoolsInner) SetPriority(v int32) {
	o.Priority = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *LoadBalancerUpdatePoolsInner) SetMethod(v string) {
	o.Method = &v
}

// GetKeepalive returns the Keepalive field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetKeepalive() string {
	if o == nil || IsNil(o.Keepalive) {
		var ret string
		return ret
	}
	return *o.Keepalive
}

// GetKeepaliveOk returns a tuple with the Keepalive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetKeepaliveOk() (*string, bool) {
	if o == nil || IsNil(o.Keepalive) {
		return nil, false
	}
	return o.Keepalive, true
}

// HasKeepalive returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasKeepalive() bool {
	if o != nil && !IsNil(o.Keepalive) {
		return true
	}

	return false
}

// SetKeepalive gets a reference to the given string and assigns it to the Keepalive field.
func (o *LoadBalancerUpdatePoolsInner) SetKeepalive(v string) {
	o.Keepalive = &v
}

// GetNextUpstreamTcp returns the NextUpstreamTcp field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetNextUpstreamTcp() string {
	if o == nil || IsNil(o.NextUpstreamTcp) {
		var ret string
		return ret
	}
	return *o.NextUpstreamTcp
}

// GetNextUpstreamTcpOk returns a tuple with the NextUpstreamTcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetNextUpstreamTcpOk() (*string, bool) {
	if o == nil || IsNil(o.NextUpstreamTcp) {
		return nil, false
	}
	return o.NextUpstreamTcp, true
}

// HasNextUpstreamTcp returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasNextUpstreamTcp() bool {
	if o != nil && !IsNil(o.NextUpstreamTcp) {
		return true
	}

	return false
}

// SetNextUpstreamTcp gets a reference to the given string and assigns it to the NextUpstreamTcp field.
func (o *LoadBalancerUpdatePoolsInner) SetNextUpstreamTcp(v string) {
	o.NextUpstreamTcp = &v
}

// GetNextUpstreamTcpCodes returns the NextUpstreamTcpCodes field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetNextUpstreamTcpCodes() NextUpstreamTcpCodes {
	if o == nil || IsNil(o.NextUpstreamTcpCodes) {
		var ret NextUpstreamTcpCodes
		return ret
	}
	return *o.NextUpstreamTcpCodes
}

// GetNextUpstreamTcpCodesOk returns a tuple with the NextUpstreamTcpCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetNextUpstreamTcpCodesOk() (*NextUpstreamTcpCodes, bool) {
	if o == nil || IsNil(o.NextUpstreamTcpCodes) {
		return nil, false
	}
	return o.NextUpstreamTcpCodes, true
}

// HasNextUpstreamTcpCodes returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasNextUpstreamTcpCodes() bool {
	if o != nil && !IsNil(o.NextUpstreamTcpCodes) {
		return true
	}

	return false
}

// SetNextUpstreamTcpCodes gets a reference to the given NextUpstreamTcpCodes and assigns it to the NextUpstreamTcpCodes field.
func (o *LoadBalancerUpdatePoolsInner) SetNextUpstreamTcpCodes(v NextUpstreamTcpCodes) {
	o.NextUpstreamTcpCodes = &v
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetRegions() []string {
	if o == nil || IsNil(o.Regions) {
		var ret []string
		return ret
	}
	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetRegionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Regions) {
		return nil, false
	}
	return o.Regions, true
}

// HasRegions returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasRegions() bool {
	if o != nil && !IsNil(o.Regions) {
		return true
	}

	return false
}

// SetRegions gets a reference to the given []string and assigns it to the Regions field.
func (o *LoadBalancerUpdatePoolsInner) SetRegions(v []string) {
	o.Regions = v
}

// GetMonitoringStatus returns the MonitoringStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoadBalancerUpdatePoolsInner) GetMonitoringStatus() MonitoringStatus {
	if o == nil || IsNil(o.MonitoringStatus.Get()) {
		var ret MonitoringStatus
		return ret
	}
	return *o.MonitoringStatus.Get()
}

// GetMonitoringStatusOk returns a tuple with the MonitoringStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoadBalancerUpdatePoolsInner) GetMonitoringStatusOk() (*MonitoringStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.MonitoringStatus.Get(), o.MonitoringStatus.IsSet()
}

// HasMonitoringStatus returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasMonitoringStatus() bool {
	if o != nil && o.MonitoringStatus.IsSet() {
		return true
	}

	return false
}

// SetMonitoringStatus gets a reference to the given NullableMonitoringStatus and assigns it to the MonitoringStatus field.
func (o *LoadBalancerUpdatePoolsInner) SetMonitoringStatus(v MonitoringStatus) {
	o.MonitoringStatus.Set(&v)
}
// SetMonitoringStatusNil sets the value for MonitoringStatus to be an explicit nil
func (o *LoadBalancerUpdatePoolsInner) SetMonitoringStatusNil() {
	o.MonitoringStatus.Set(nil)
}

// UnsetMonitoringStatus ensures that no value is present for MonitoringStatus, not even an explicit nil
func (o *LoadBalancerUpdatePoolsInner) UnsetMonitoringStatus() {
	o.MonitoringStatus.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *LoadBalancerUpdatePoolsInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *LoadBalancerUpdatePoolsInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerUpdatePoolsInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *LoadBalancerUpdatePoolsInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *LoadBalancerUpdatePoolsInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o LoadBalancerUpdatePoolsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoadBalancerUpdatePoolsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Origins) {
		toSerialize["origins"] = o.Origins
	}
	// skip: id is readOnly
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.Keepalive) {
		toSerialize["keepalive"] = o.Keepalive
	}
	if !IsNil(o.NextUpstreamTcp) {
		toSerialize["next_upstream_tcp"] = o.NextUpstreamTcp
	}
	if !IsNil(o.NextUpstreamTcpCodes) {
		toSerialize["next_upstream_tcp_codes"] = o.NextUpstreamTcpCodes
	}
	if !IsNil(o.Regions) {
		toSerialize["regions"] = o.Regions
	}
	if o.MonitoringStatus.IsSet() {
		toSerialize["monitoring_status"] = o.MonitoringStatus.Get()
	}
	// skip: created_at is readOnly
	// skip: updated_at is readOnly
	return toSerialize, nil
}

type NullableLoadBalancerUpdatePoolsInner struct {
	value *LoadBalancerUpdatePoolsInner
	isSet bool
}

func (v NullableLoadBalancerUpdatePoolsInner) Get() *LoadBalancerUpdatePoolsInner {
	return v.value
}

func (v *NullableLoadBalancerUpdatePoolsInner) Set(val *LoadBalancerUpdatePoolsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableLoadBalancerUpdatePoolsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableLoadBalancerUpdatePoolsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoadBalancerUpdatePoolsInner(val *LoadBalancerUpdatePoolsInner) *NullableLoadBalancerUpdatePoolsInner {
	return &NullableLoadBalancerUpdatePoolsInner{value: val, isSet: true}
}

func (v NullableLoadBalancerUpdatePoolsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoadBalancerUpdatePoolsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


